// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> Audited object Types. </summary>
    public enum AuditedObjectType
    {
        /// <summary> AUTHENTICATION. </summary>
        Authentication,
        /// <summary> TENANT_USER. </summary>
        TenantUser,
        /// <summary> PROCESS. </summary>
        Process,
        /// <summary> PROCESS_PAGE_ITEM. </summary>
        ProcessPageItem,
        /// <summary> TASK. </summary>
        Task,
        /// <summary> TASK_PAGE_ITEM. </summary>
        TaskPageItem,
        /// <summary> WORKER. </summary>
        Worker,
        /// <summary> ROBOT. </summary>
        Robot
    }
}
