// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;

namespace KuFlow.Rest.Models
{
    public partial class AuthenticationEngineCertificate
    {
        internal static AuthenticationEngineCertificate DeserializeAuthenticationEngineCertificate(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string @namespace = default;
            AuthenticationEngineCertificateTls tls = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("namespace"u8))
                {
                    @namespace = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("tls"u8))
                {
                    tls = AuthenticationEngineCertificateTls.DeserializeAuthenticationEngineCertificateTls(property.Value);
                    continue;
                }
            }
            return new AuthenticationEngineCertificate(@namespace, tls);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static AuthenticationEngineCertificate FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeAuthenticationEngineCertificate(document.RootElement);
        }
    }
}
