// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> The AuthenticationType. </summary>
    public enum AuthenticationType
    {
        /// <summary> ENGINE_TOKEN. </summary>
        EngineToken,
        /// <summary> ENGINE_CERTIFICATE. </summary>
        EngineCertificate
    }
}
