// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    /// <summary> The AuthenticationCreateParams. </summary>
    public partial class AuthenticationCreateParams
    {
        /// <summary> Initializes a new instance of <see cref="AuthenticationCreateParams"/>. </summary>
        /// <param name="type"></param>
        public AuthenticationCreateParams(AuthenticationType type)
        {
            Type = type;
        }

        /// <summary> Initializes a new instance of <see cref="AuthenticationCreateParams"/>. </summary>
        /// <param name="type"></param>
        /// <param name="tenantId"> Tenant id. This attribute is required when an OAuth2 authentication is used. </param>
        internal AuthenticationCreateParams(AuthenticationType type, Guid? tenantId)
        {
            Type = type;
            TenantId = tenantId;
        }

        /// <summary> Gets the type. </summary>
        public AuthenticationType Type { get; }
        /// <summary> Tenant id. This attribute is required when an OAuth2 authentication is used. </summary>
        public Guid? TenantId { get; set; }
    }
}
