// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KuFlow.Rest.Models
{
    public partial class AuthenticationEngineCertificateTls : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("serverRootCaCertificate"u8);
            writer.WriteStringValue(ServerRootCaCertificate);
            writer.WritePropertyName("clientCertificate"u8);
            writer.WriteStringValue(ClientCertificate);
            writer.WritePropertyName("clientPrivateKey"u8);
            writer.WriteStringValue(ClientPrivateKey);
            writer.WriteEndObject();
        }

        internal static AuthenticationEngineCertificateTls DeserializeAuthenticationEngineCertificateTls(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string serverRootCaCertificate = default;
            string clientCertificate = default;
            string clientPrivateKey = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("serverRootCaCertificate"u8))
                {
                    serverRootCaCertificate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("clientCertificate"u8))
                {
                    clientCertificate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("clientPrivateKey"u8))
                {
                    clientPrivateKey = property.Value.GetString();
                    continue;
                }
            }
            return new AuthenticationEngineCertificateTls(serverRootCaCertificate, clientCertificate, clientPrivateKey);
        }
    }
}
