// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KuFlow.Rest.Models
{
    public partial class AuthenticationEngineCertificate : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("namespace"u8);
            writer.WriteStringValue(Namespace);
            writer.WritePropertyName("tls"u8);
            writer.WriteObjectValue(Tls);
            writer.WriteEndObject();
        }

        internal static AuthenticationEngineCertificate DeserializeAuthenticationEngineCertificate(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string @namespace = default;
            AuthenticationEngineCertificateTls tls = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("namespace"u8))
                {
                    @namespace = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("tls"u8))
                {
                    tls = AuthenticationEngineCertificateTls.DeserializeAuthenticationEngineCertificateTls(property.Value);
                    continue;
                }
            }
            return new AuthenticationEngineCertificate(@namespace, tls);
        }
    }
}
