// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    /// <summary> The Authentication. </summary>
    public partial class Authentication : AbstractAudited
    {
        /// <summary> Initializes a new instance of <see cref="Authentication"/>. </summary>
        public Authentication()
        {
        }

        /// <summary> Initializes a new instance of <see cref="Authentication"/>. </summary>
        /// <param name="objectType"> Audited object Types. </param>
        /// <param name="createdBy"> Who create this model. </param>
        /// <param name="createdAt"> When this model was created. </param>
        /// <param name="lastModifiedBy"> Who was last update this model. </param>
        /// <param name="lastModifiedAt"> When this model type was last updated. </param>
        /// <param name="id"></param>
        /// <param name="type"></param>
        /// <param name="tenantId"> Tenant id. This attribute is required when an OAuth2 authentication is used. </param>
        /// <param name="token">
        /// Engine authentication token.
        ///
        /// @deprecated use engineToken.token
        ///
        /// </param>
        /// <param name="expiredAt">
        /// Engine authentication token expiration.
        ///
        /// @deprecated use engineToken.expiredAt
        ///
        /// </param>
        /// <param name="engineToken"></param>
        /// <param name="engineCertificate"></param>
        internal Authentication(AuditedObjectType? objectType, Guid? createdBy, DateTimeOffset? createdAt, Guid? lastModifiedBy, DateTimeOffset? lastModifiedAt, Guid? id, AuthenticationType? type, Guid? tenantId, string token, DateTimeOffset? expiredAt, AuthenticationEngineToken engineToken, AuthenticationEngineCertificate engineCertificate) : base(objectType, createdBy, createdAt, lastModifiedBy, lastModifiedAt)
        {
            Id = id;
            Type = type;
            TenantId = tenantId;
            Token = token;
            ExpiredAt = expiredAt;
            EngineToken = engineToken;
            EngineCertificate = engineCertificate;
        }

        /// <summary> Gets or sets the id. </summary>
        public Guid? Id { get; set; }
        /// <summary> Gets or sets the type. </summary>
        public AuthenticationType? Type { get; set; }
        /// <summary> Tenant id. This attribute is required when an OAuth2 authentication is used. </summary>
        public Guid? TenantId { get; set; }
        /// <summary>
        /// Engine authentication token.
        ///
        /// @deprecated use engineToken.token
        ///
        /// </summary>
        public string Token { get; set; }
        /// <summary>
        /// Engine authentication token expiration.
        ///
        /// @deprecated use engineToken.expiredAt
        ///
        /// </summary>
        public DateTimeOffset? ExpiredAt { get; set; }
        /// <summary> Gets or sets the engine token. </summary>
        public AuthenticationEngineToken EngineToken { get; set; }
        /// <summary> Gets or sets the engine certificate. </summary>
        public AuthenticationEngineCertificate EngineCertificate { get; set; }
    }
}
