// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace KuFlow.Rest.Models
{
    /// <summary> The AuthenticationEngineCertificate. </summary>
    public partial class AuthenticationEngineCertificate
    {
        /// <summary> Initializes a new instance of <see cref="AuthenticationEngineCertificate"/>. </summary>
        /// <param name="namespace"></param>
        /// <param name="tls"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="namespace"/> or <paramref name="tls"/> is null. </exception>
        public AuthenticationEngineCertificate(string @namespace, AuthenticationEngineCertificateTls tls)
        {
            Argument.AssertNotNull(@namespace, nameof(@namespace));
            Argument.AssertNotNull(tls, nameof(tls));

            Namespace = @namespace;
            Tls = tls;
        }

        /// <summary> Gets or sets the namespace. </summary>
        public string Namespace { get; set; }
        /// <summary> Gets or sets the tls. </summary>
        public AuthenticationEngineCertificateTls Tls { get; set; }
    }
}
