// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class AuthenticationTypeExtensions
    {
        public static string ToSerialString(this AuthenticationType value) => value switch
        {
            AuthenticationType.EngineToken => "ENGINE_TOKEN",
            AuthenticationType.EngineCertificate => "ENGINE_CERTIFICATE",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown AuthenticationType value.")
        };

        public static AuthenticationType ToAuthenticationType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "ENGINE_TOKEN")) return AuthenticationType.EngineToken;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "ENGINE_CERTIFICATE")) return AuthenticationType.EngineCertificate;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown AuthenticationType value.");
        }
    }
}
