// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    /// <summary> The AuthenticationEngineToken. </summary>
    public partial class AuthenticationEngineToken
    {
        /// <summary> Initializes a new instance of <see cref="AuthenticationEngineToken"/>. </summary>
        /// <param name="token"> Engine authentication token. </param>
        /// <param name="expiredAt"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="token"/> is null. </exception>
        internal AuthenticationEngineToken(string token, DateTimeOffset expiredAt)
        {
            Argument.AssertNotNull(token, nameof(token));

            Token = token;
            ExpiredAt = expiredAt;
        }

        /// <summary> Engine authentication token. </summary>
        public string Token { get; }
        /// <summary> Gets the expired at. </summary>
        public DateTimeOffset ExpiredAt { get; }
    }
}
