// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class JsonPatchOperationTypeExtensions
    {
        public static string ToSerialString(this JsonPatchOperationType value) => value switch
        {
            JsonPatchOperationType.Add => "add",
            JsonPatchOperationType.Remove => "remove",
            JsonPatchOperationType.Replace => "replace",
            JsonPatchOperationType.Move => "move",
            JsonPatchOperationType.Copy => "copy",
            JsonPatchOperationType.Test => "test",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown JsonPatchOperationType value.")
        };

        public static JsonPatchOperationType ToJsonPatchOperationType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "add")) return JsonPatchOperationType.Add;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "remove")) return JsonPatchOperationType.Remove;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "replace")) return JsonPatchOperationType.Replace;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "move")) return JsonPatchOperationType.Move;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "copy")) return JsonPatchOperationType.Copy;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "test")) return JsonPatchOperationType.Test;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown JsonPatchOperationType value.");
        }
    }
}
