// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;

namespace KuFlow.Rest.Models
{
  public partial class JsonValueError
  {
    internal static JsonValueError DeserializeJsonValueError(JsonElement element)
    {
      if (element.ValueKind == JsonValueKind.Null)
      {
        return null;
      }
      string propertyPath = default;
      string type = default;
      foreach (var property in element.EnumerateObject())
      {
        if (property.NameEquals("propertyPath"u8))
        {
          propertyPath = property.Value.GetString();
          continue;
        }
        if (property.NameEquals("type"u8))
        {
          type = property.Value.GetString();
          continue;
        }
      }
      return new JsonValueError(propertyPath, type);
    }

    /// <summary> Deserializes the model from a raw response. </summary>
    /// <param name="response"> The response to deserialize the model from. </param>
    internal static JsonValueError FromResponse(Response response)
    {
      using var document = JsonDocument.Parse(response.Content);
      return DeserializeJsonValueError(document.RootElement);
    }
  }
}
