// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> The operation to perform. </summary>
    public enum JsonPatchOperationType
    {
        /// <summary> add. </summary>
        Add,
        /// <summary> remove. </summary>
        Remove,
        /// <summary> replace. </summary>
        Replace,
        /// <summary> move. </summary>
        Move,
        /// <summary> copy. </summary>
        Copy,
        /// <summary> test. </summary>
        Test
    }
}
