// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure;

namespace KuFlow.Rest.Models
{
  public partial class KmsKey
  {
    internal static KmsKey DeserializeKmsKey(JsonElement element)
    {
      if (element.ValueKind == JsonValueKind.Null)
      {
        return null;
      }
      string id = default;
      byte[] value = default;
      foreach (var property in element.EnumerateObject())
      {
        if (property.NameEquals("id"u8))
        {
          id = property.Value.GetString();
          continue;
        }
        if (property.NameEquals("value"u8))
        {
          value = property.Value.GetBytesFromBase64("D");
          continue;
        }
      }
      return new KmsKey(id, value);
    }

    /// <summary> Deserializes the model from a raw response. </summary>
    /// <param name="response"> The response to deserialize the model from. </param>
    internal static KmsKey FromResponse(Response response)
    {
      using var document = JsonDocument.Parse(response.Content);
      return DeserializeKmsKey(document.RootElement);
    }
  }
}
