// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> Paged Model types. </summary>
    public enum PagedObjectType
    {
        /// <summary> PRINCIPAL_PAGE. </summary>
        PrincipalPage,
        /// <summary> TENANT_USER_PAGE. </summary>
        TenantUserPage,
        /// <summary> PROCESS_PAGE. </summary>
        ProcessPage,
        /// <summary> TASK_PAGE. </summary>
        TaskPage,
        /// <summary> ROBOT_PAGE. </summary>
        RobotPage
    }
}
