// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace KuFlow.Rest.Models
{
    /// <summary> The Page. </summary>
    public partial class Page
    {
        /// <summary> Initializes a new instance of <see cref="Page"/>. </summary>
        /// <param name="metadata"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="metadata"/> is null. </exception>
        internal Page(PageMetadata metadata)
        {
            Argument.AssertNotNull(metadata, nameof(metadata));

            Metadata = metadata;
        }

        /// <summary> Initializes a new instance of <see cref="Page"/>. </summary>
        /// <param name="objectType"> Paged Model types. </param>
        /// <param name="metadata"></param>
        internal Page(PagedObjectType? objectType, PageMetadata metadata)
        {
            ObjectType = objectType;
            Metadata = metadata;
        }

        /// <summary> Paged Model types. </summary>
        public PagedObjectType? ObjectType { get; }
        /// <summary> Gets the metadata. </summary>
        public PageMetadata Metadata { get; }
    }
}
