// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    /// <summary> The PrincipalApplication. </summary>
    public partial class PrincipalApplication
    {
        /// <summary> Initializes a new instance of <see cref="PrincipalApplication"/>. </summary>
        internal PrincipalApplication()
        {
        }

        /// <summary> Initializes a new instance of <see cref="PrincipalApplication"/>. </summary>
        /// <param name="id"></param>
        internal PrincipalApplication(Guid? id)
        {
            Id = id;
        }

        /// <summary> Gets the id. </summary>
        public Guid? Id { get; }
    }
}
