// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KuFlow.Rest.Models
{
  public partial class ProcessItemTaskAppendLogParams : IUtf8JsonSerializable
  {
    void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
    {
      writer.WriteStartObject();
      writer.WritePropertyName("message"u8);
      writer.WriteStringValue(Message);
      writer.WritePropertyName("level"u8);
      writer.WriteStringValue(Level.ToString());
      writer.WriteEndObject();
    }

    /// <summary> Convert into a <see cref="RequestContent"/>. </summary>
    internal virtual RequestContent ToRequestContent()
    {
      var content = new Utf8JsonRequestContent();
      content.JsonWriter.WriteObjectValue(this);
      return content;
    }
  }
}
