// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> The ProcessItemMessageCreateParams. </summary>
    public partial class ProcessItemMessageCreateParams
    {
        /// <summary> Initializes a new instance of <see cref="ProcessItemMessageCreateParams"/>. </summary>
        public ProcessItemMessageCreateParams()
        {
        }

        /// <summary> Initializes a new instance of <see cref="ProcessItemMessageCreateParams"/>. </summary>
        /// <param name="text"></param>
        /// <param name="data"> Json value. </param>
        /// <param name="dataStructureDataDefinitionCode"></param>
        internal ProcessItemMessageCreateParams(string text, JsonValue data, string dataStructureDataDefinitionCode)
        {
            Text = text;
            Data = data;
            DataStructureDataDefinitionCode = dataStructureDataDefinitionCode;
        }

        /// <summary> Gets or sets the text. </summary>
        public string Text { get; set; }
        /// <summary> Json value. </summary>
        public JsonValue Data { get; set; }
        /// <summary> Gets or sets the data structure data definition code. </summary>
        public string DataStructureDataDefinitionCode { get; set; }
    }
}
