// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;

namespace KuFlow.Rest.Models
{
    public partial class ProcessSaveEntityDocumentResponseCommand
    {
        internal static ProcessSaveEntityDocumentResponseCommand DeserializeProcessSaveEntityDocumentResponseCommand(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string value = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("value"u8))
                {
                    value = property.Value.GetString();
                    continue;
                }
            }
            return new ProcessSaveEntityDocumentResponseCommand(value);
        }
    }
}
