// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> The ProcessItemTaskLogLevel. </summary>
    public enum ProcessItemTaskLogLevel
    {
        /// <summary> INFO. </summary>
        Info,
        /// <summary> WARN. </summary>
        Warn,
        /// <summary> ERROR. </summary>
        Error
    }
}
