// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> The ProcessElementValueNumber. </summary>
    public partial class ProcessElementValueNumber : ProcessElementValue
    {
        /// <summary> Initializes a new instance of <see cref="ProcessElementValueNumber"/>. </summary>
        public ProcessElementValueNumber()
        {
            Type = ProcessElementValueType.Number;
        }

        /// <summary> Initializes a new instance of <see cref="ProcessElementValueNumber"/>. </summary>
        /// <param name="valid"></param>
        /// <param name="type"> Process element value types. </param>
        /// <param name="value"></param>
        internal ProcessElementValueNumber(bool? valid, ProcessElementValueType type, double? value) : base(valid, type)
        {
            Value = value;
            Type = type;
        }

        /// <summary> Gets or sets the value. </summary>
        public double? Value { get; set; }
    }
}
