// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> Process Item Task state. </summary>
    public enum ProcessItemTaskState
    {
        /// <summary> READY. </summary>
        Ready,
        /// <summary> CLAIMED. </summary>
        Claimed,
        /// <summary> COMPLETED. </summary>
        Completed,
        /// <summary> CANCELLED. </summary>
        Cancelled
    }
}
