// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> The ProcessItemTaskPageItem. </summary>
    public partial class ProcessItemTaskPageItem
    {
        /// <summary> Initializes a new instance of <see cref="ProcessItemTaskPageItem"/>. </summary>
        /// <param name="state"> Process Item Task state. </param>
        internal ProcessItemTaskPageItem(ProcessItemTaskState state)
        {
            State = state;
        }

        /// <summary> Process Item Task state. </summary>
        public ProcessItemTaskState State { get; }
    }
}
