// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace KuFlow.Rest.Models
{
  public partial class ProcessItemMessageCreateParams : IUtf8JsonSerializable
  {
    void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
    {
      writer.WriteStartObject();
      if (Optional.IsDefined(Text))
      {
        writer.WritePropertyName("text"u8);
        writer.WriteStringValue(Text);
      }
      if (Optional.IsDefined(Data))
      {
        writer.WritePropertyName("data"u8);
        writer.WriteObjectValue(Data);
      }
      if (Optional.IsDefined(DataStructureDataDefinitionCode))
      {
        writer.WritePropertyName("dataStructureDataDefinitionCode"u8);
        writer.WriteStringValue(DataStructureDataDefinitionCode);
      }
      writer.WriteEndObject();
    }

    /// <summary> Convert into a <see cref="RequestContent"/>. </summary>
    internal virtual RequestContent ToRequestContent()
    {
      var content = new Utf8JsonRequestContent();
      content.JsonWriter.WriteObjectValue(this);
      return content;
    }
  }
}
