// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class ProcessItemTypeExtensions
    {
        public static string ToSerialString(this ProcessItemType value) => value switch
        {
            ProcessItemType.Task => "TASK",
            ProcessItemType.Message => "MESSAGE",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown ProcessItemType value.")
        };

        public static ProcessItemType ToProcessItemType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "TASK")) return ProcessItemType.Task;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "MESSAGE")) return ProcessItemType.Message;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown ProcessItemType value.");
        }
    }
}
