// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class RobotAssetTypeExtensions
    {
        public static string ToSerialString(this RobotAssetType value) => value switch
        {
            RobotAssetType.Python => "PYTHON",
            RobotAssetType.PythonPip => "PYTHON_PIP",
            RobotAssetType.NodeJS => "NODEJS",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotAssetType value.")
        };

        public static RobotAssetType ToRobotAssetType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "PYTHON")) return RobotAssetType.Python;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "PYTHON_PIP")) return RobotAssetType.PythonPip;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "NODEJS")) return RobotAssetType.NodeJS;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotAssetType value.");
        }
    }
}
