// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace KuFlow.Rest.Models
{
    /// <summary> The Robot. </summary>
    public partial class Robot : AbstractAudited
    {
        /// <summary> Initializes a new instance of <see cref="Robot"/>. </summary>
        /// <param name="id"> Robot ID. </param>
        /// <param name="code"> Robot Code. </param>
        /// <param name="name"> Robot name. </param>
        /// <param name="sourceType"> Robot source type. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="code"/> or <paramref name="name"/> is null. </exception>
        public Robot(Guid id, string code, string name, RobotSourceType sourceType)
        {
            Argument.AssertNotNull(code, nameof(code));
            Argument.AssertNotNull(name, nameof(name));

            Id = id;
            Code = code;
            Name = name;
            SourceType = sourceType;
            EnvironmentVariables = new ChangeTrackingDictionary<string, string>();
        }

        /// <summary> Initializes a new instance of <see cref="Robot"/>. </summary>
        /// <param name="objectType"> Audited object Types. </param>
        /// <param name="createdBy"> Who create this model. </param>
        /// <param name="createdAt"> When this model was created. </param>
        /// <param name="lastModifiedBy"> Who was last update this model. </param>
        /// <param name="lastModifiedAt"> When this model type was last updated. </param>
        /// <param name="id"> Robot ID. </param>
        /// <param name="code"> Robot Code. </param>
        /// <param name="name"> Robot name. </param>
        /// <param name="description"> Robot description. </param>
        /// <param name="sourceType"> Robot source type. </param>
        /// <param name="sourceFile"> Robot source type. </param>
        /// <param name="environmentVariables"> Environment variables to load when the robot is executed. </param>
        /// <param name="tenantId"> Tenant ID. </param>
        internal Robot(AuditedObjectType? objectType, Guid? createdBy, DateTimeOffset? createdAt, Guid? lastModifiedBy, DateTimeOffset? lastModifiedAt, Guid id, string code, string name, string description, RobotSourceType sourceType, RobotSourceFile sourceFile, IDictionary<string, string> environmentVariables, Guid? tenantId) : base(objectType, createdBy, createdAt, lastModifiedBy, lastModifiedAt)
        {
            Id = id;
            Code = code;
            Name = name;
            Description = description;
            SourceType = sourceType;
            SourceFile = sourceFile;
            EnvironmentVariables = environmentVariables;
            TenantId = tenantId;
        }

        /// <summary> Robot ID. </summary>
        public Guid Id { get; set; }
        /// <summary> Robot Code. </summary>
        public string Code { get; set; }
        /// <summary> Robot name. </summary>
        public string Name { get; set; }
        /// <summary> Robot description. </summary>
        public string Description { get; set; }
        /// <summary> Robot source type. </summary>
        public RobotSourceType SourceType { get; set; }
        /// <summary> Robot source type. </summary>
        public RobotSourceFile SourceFile { get; set; }
        /// <summary> Environment variables to load when the robot is executed. </summary>
        public IDictionary<string, string> EnvironmentVariables { get; }
        /// <summary> Tenant ID. </summary>
        public Guid? TenantId { get; set; }
    }
}
