// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> Robot asset type. </summary>
    public enum RobotAssetType
    {
        /// <summary> PYTHON. </summary>
        Python,
        /// <summary> PYTHON_PIP. </summary>
        PythonPip,
        /// <summary> NODEJS. </summary>
        NodeJS
    }
}
