// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> Robot asset platform architecture. </summary>
    public enum RobotAssetArchitecture
    {
        /// <summary> X86_32. </summary>
        X86Bit32,
        /// <summary> X86_64. </summary>
        X86Bit64
    }
}
