// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class RobotFilterContextExtensions
    {
        public static string ToSerialString(this RobotFilterContext value) => value switch
        {
            RobotFilterContext.Ready => "READY",
            RobotFilterContext.Default => "DEFAULT",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotFilterContext value.")
        };

        public static RobotFilterContext ToRobotFilterContext(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "READY")) return RobotFilterContext.Ready;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "DEFAULT")) return RobotFilterContext.Default;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotFilterContext value.");
        }
    }
}
