// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class RobotSourceTypeExtensions
    {
        public static string ToSerialString(this RobotSourceType value) => value switch
        {
            RobotSourceType.Package => "PACKAGE",
            RobotSourceType.Unknown => "UNKNOWN",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotSourceType value.")
        };

        public static RobotSourceType ToRobotSourceType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "PACKAGE")) return RobotSourceType.Package;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "UNKNOWN")) return RobotSourceType.Unknown;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotSourceType value.");
        }
    }
}
