// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> Robot source type. </summary>
    public enum RobotSourceType
    {
        /// <summary> PACKAGE. </summary>
        Package,
        /// <summary> ROBOT_FRAMEWORK_PYTHON_WHEEL. </summary>
        RobotFrameworkPythonWheel
    }
}
