// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class RobotAssetPlatformExtensions
    {
        public static string ToSerialString(this RobotAssetPlatform value) => value switch
        {
            RobotAssetPlatform.Windows => "WINDOWS",
            RobotAssetPlatform.MacOS => "MAC_OS",
            RobotAssetPlatform.Linux => "LINUX",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotAssetPlatform value.")
        };

        public static RobotAssetPlatform ToRobotAssetPlatform(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "WINDOWS")) return RobotAssetPlatform.Windows;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "MAC_OS")) return RobotAssetPlatform.MacOS;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "LINUX")) return RobotAssetPlatform.Linux;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown RobotAssetPlatform value.");
        }
    }
}
