// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace KuFlow.Rest.Models
{
    /// <summary> The TaskSaveJsonFormsValueDataCommand. </summary>
    public partial class TaskSaveJsonFormsValueDataCommand
    {
        /// <summary> Initializes a new instance of <see cref="TaskSaveJsonFormsValueDataCommand"/>. </summary>
        public TaskSaveJsonFormsValueDataCommand()
        {
            Data = new ChangeTrackingDictionary<string, object>();
        }

        /// <summary> Initializes a new instance of <see cref="TaskSaveJsonFormsValueDataCommand"/>. </summary>
        /// <param name="data"> json value filled that complain with the related json schema. </param>
        internal TaskSaveJsonFormsValueDataCommand(IDictionary<string, object> data)
        {
            Data = data;
        }

        /// <summary> json value filled that complain with the related json schema. </summary>
        public IDictionary<string, object> Data { get; }
    }
}
