// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    /// <summary> Command to assign task, only one option is required. </summary>
    public partial class TaskAssignCommand
    {
        /// <summary> Initializes a new instance of <see cref="TaskAssignCommand"/>. </summary>
        public TaskAssignCommand()
        {
        }

        /// <summary> Initializes a new instance of <see cref="TaskAssignCommand"/>. </summary>
        /// <param name="principalId"></param>
        /// <param name="email"></param>
        internal TaskAssignCommand(Guid? principalId, string email)
        {
            PrincipalId = principalId;
            Email = email;
        }

        /// <summary> Gets or sets the principal id. </summary>
        public Guid? PrincipalId { get; set; }
        /// <summary> Gets or sets the email. </summary>
        public string Email { get; set; }
    }
}
