// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    internal static partial class TenantPricingPlanExtensions
    {
        public static string ToSerialString(this TenantPricingPlan value) => value switch
        {
            TenantPricingPlan.Free => "FREE",
            TenantPricingPlan.Premium => "PREMIUM",
            TenantPricingPlan.Unlimited => "UNLIMITED",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown TenantPricingPlan value.")
        };

        public static TenantPricingPlan ToTenantPricingPlan(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "FREE")) return TenantPricingPlan.Free;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "PREMIUM")) return TenantPricingPlan.Premium;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "UNLIMITED")) return TenantPricingPlan.Unlimited;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown TenantPricingPlan value.");
        }
    }
}
