// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace KuFlow.Rest.Models
{
    public partial class TenantUserPage
    {
        internal static TenantUserPage DeserializeTenantUserPage(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            IReadOnlyList<TenantUser> content = default;
            Optional<PagedObjectType> objectType = default;
            PageMetadata metadata = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("content"u8))
                {
                    List<TenantUser> array = new List<TenantUser>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(TenantUser.DeserializeTenantUser(item));
                    }
                    content = array;
                    continue;
                }
                if (property.NameEquals("objectType"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    objectType = property.Value.GetString().ToPagedObjectType();
                    continue;
                }
                if (property.NameEquals("metadata"u8))
                {
                    metadata = PageMetadata.DeserializePageMetadata(property.Value);
                    continue;
                }
            }
            return new TenantUserPage(Optional.ToNullable(objectType), metadata, content);
        }
    }
}
