// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace KuFlow.Rest.Models
{
    /// <summary> The WebhookEventProcessItemCreatedData. </summary>
    internal partial class WebhookEventProcessItemCreatedData
    {
        /// <summary> Initializes a new instance of <see cref="WebhookEventProcessItemCreatedData"/>. </summary>
        /// <param name="processId"></param>
        /// <param name="processItemId"></param>
        /// <param name="processItemType"> Process Item Type. </param>
        internal WebhookEventProcessItemCreatedData(Guid processId, Guid processItemId, ProcessItemType processItemType)
        {
            ProcessId = processId;
            ProcessItemId = processItemId;
            ProcessItemType = processItemType;
        }

        /// <summary> Initializes a new instance of <see cref="WebhookEventProcessItemCreatedData"/>. </summary>
        /// <param name="processId"></param>
        /// <param name="processItemId"></param>
        /// <param name="processItemType"> Process Item Type. </param>
        /// <param name="processItemTaskCode"></param>
        /// <param name="processItemState"> Process Item Task state. </param>
        internal WebhookEventProcessItemCreatedData(Guid processId, Guid processItemId, ProcessItemType processItemType, string processItemTaskCode, ProcessItemTaskState? processItemState)
        {
            ProcessId = processId;
            ProcessItemId = processItemId;
            ProcessItemType = processItemType;
            ProcessItemTaskCode = processItemTaskCode;
            ProcessItemState = processItemState;
        }

        /// <summary> Gets the process id. </summary>
        public Guid ProcessId { get; }
        /// <summary> Gets the process item id. </summary>
        public Guid ProcessItemId { get; }
        /// <summary> Process Item Type. </summary>
        public ProcessItemType ProcessItemType { get; }
        /// <summary> Gets the process item task code. </summary>
        public string ProcessItemTaskCode { get; }
        /// <summary> Process Item Task state. </summary>
        public ProcessItemTaskState? ProcessItemState { get; }
    }
}
