// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace KuFlow.Rest.Models
{
    /// <summary> Type of the Event. </summary>
    internal enum WebhookType
    {
        /// <summary> PROCESS.CREATED. </summary>
        ProcessCreated,
        /// <summary> PROCESS.STATE_CHANGED. </summary>
        ProcessStateChanged,
        /// <summary> PROCESS_ITEM.CREATED. </summary>
        ProcessItemCreated,
        /// <summary> PROCESS_ITEM.TASK_STATE_CHANGED. </summary>
        ProcessItemTaskStateChanged
    }
}
